#base image
FROM ubuntu

# maintainer
#MAINTAINER Your Name <your.email@example.com>
# install dependencies
# RUN apt-get update && \
#     apt-get install -y \
#     build-essential \
#     curl \
#     git \
#     wget \
#     python3 \
#     python3-pip \
#     python3-venv && \
#     rm -rf /var/lib/apt/lists/*
# # set the working directory
# WORKDIR /app

# Run a command to verify the installation
# RUN python3 --version && \
#     pip3 --version
# Expose a port if needed (optional)
# EXPOSE 8000

#CMD to run the application (optional)
# CMD ["python3", "app.py"]
# Note: You can add more commands to install specific Python packages or set up your application as needed.
CMD [ "echo","Hello World" ]
